# Generated by Django 4.0.2 on 2022-03-01 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_buildingmanager_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='user_id',
        ),
        migrations.AddField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
