# Generated by Django 4.0.2 on 2022-03-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_technician_id_technician_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='user_id',
            new_name='user',
        ),
    ]
