# Generated by Django 4.0.2 on 2022-04-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_user_id_technician_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='user',
            new_name='id',
        ),
    ]
