# Generated by Django 4.0.2 on 2022-04-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_user_technician_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='id',
            new_name='user',
        ),
    ]
