# Generated by Django 4.0.2 on 2022-04-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_buildingmanager_users'),
        ('base', '0005_rename_id_technician_user'),
    ]

    operations = [
    ]
