# Generated by Django 4.0.2 on 2022-04-05 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('is_required', models.BooleanField()),
                ('is_repeating', models.BooleanField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.profile')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.unit')),
            ],
        ),
    ]
