# Generated by Django 4.0.2 on 2022-04-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='service_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='records.servicevisit'),
        ),
    ]
