# Generated by Django 4.0.2 on 2022-04-07 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_id_technician_user'),
        ('records', '0002_profileplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileplan',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='base.unit'),
        ),
    ]
