name: Django CI

on:
  pull_request:
    branches: [development, main]

defaults:
  run:
    working-directory: server

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        python-version: ["3.10.x"]

    steps:
      # - name: Give runner permission
      #   run: sudo chown ubuntu -R ${{github.workspace}}
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r development.txt
      - name: Run Tests
        env:
          DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
          DB_NAME: postgres
          DB_USER: postgres
          DB_PASS: postgres
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          coverage run manage.py test
      - name: Create code coverage
        run: coverage report
