name: Linter

on:
  push:
    branches-ignore:
      - "main"
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: self-hosted

    ##################
    # Load all steps #
    ##################
    steps:
      - name: Give runner permission
        run: sudo chown ubuntu -R ${{github.workspace}}
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: development
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (.*tests/.*)|(.*cypress/.*)|(.*jest/.*)
